#!/bin/bash
if [ "${1}" == '' ]; then
	shellDir="$PWD"
else
	shellDir="${1}"
fi

prefix=~/music/converted_mp3
mkdir -p "$prefix"

find "${shellDir}" -name '*.flac' -print | while read fn;
do
	ARTIST=`metaflac "$fn" --show-tag=ARTIST | sed s/.*=//g`
	TITLE=`metaflac "$fn" --show-tag=TITLE | sed s/.*=//g`
	ALBUM=`metaflac "$fn" --show-tag=ALBUM | sed s/.*=//g`
	GENRE=`metaflac "$fn" --show-tag=GENRE | sed s/.*=//g`
	TRACKNUMBER_SHORT=`metaflac "$fn" --show-tag=TRACKNUMBER | sed s/.*=//g`
	TRACKNUMBER=`printf "%02d" "$TRACKNUMBER_SHORT"`
	DATE=`metaflac "$fn" --show-tag=DATE | sed s/.*=//g`

	newpath="${prefix}/$ARTIST/$ALBUM"
	newfile="${TRACKNUMBER} - ${TITLE}.mp3"
	echo "${newpath}/${newfile}"
	mkdir -p "${newpath}"

	flac -c -d "${fn}" | lame -m j -q 0 --vbr-new -V 0 -s 44.1 - "${newpath}/${newfile}"
	id3 -t "$TITLE" -T "${TRACKNUMBER:-0}" -a "$ARTIST" -A "$ALBUM" -y "$DATE" -g "${GENRE:-12}" "${newpath}/${newfile}"

done
